cmph_tests: support -a and -f args

diff --git a/tests/cmph_compile_tests.in b/tests/cmph_compile_tests.in
--- a/tests/cmph_compile_tests.in
+++ b/tests/cmph_compile_tests.in
@@ -12,8 +12,34 @@ test -e _cwords || head -n "$N" <"${WORDS}" >_cwords
 test -e _cwords1000 || head -n 1000 <"${WORDS}" >_cwords1000
 test -e _cwords100 || head -n 100 <"${WORDS}" >_cwords100
 
+while getopts "a:f:" opt
+do
+    case "$opt" in
+        a)
+            a="$OPTARG"
+            ;;
+        f)
+            f="$OPTARG"
+            ;;
+        :)
+            echo "Error: Option -$OPTARG requires an argument" >&2
+            exit 1
+            ;;
+    esac
+    shift $((OPTIND-1))
+done
+
 # brz bmz8
-for a in chm bmz fch bdz bdz_ph chd chd_ph; do
+algos="chm bmz fch bdz bdz_ph chd chd_ph"
+if [ -n "$a" ]; then
+    algos="$a"
+fi
+hashes="jenkins wyhash crc32 fnv djb2 sdbm"
+if [ -n "$f" ]; then
+    hashes="$f"
+fi
+
+for a in $algos; do
     if [ "$a" = "bmz8" ]; then
         words=_words100
         nwords=100
@@ -25,7 +51,7 @@ for a in chm bmz fch bdz bdz_ph chd chd_ph; do
         words=_cwords
         nwords="$N"
     fi
-    for f in jenkins wyhash crc32 fnv djb2 sdbm; do
+    for f in $hashes; do
         fail=
         args="$f"
         base="${a}_${f}"
diff --git a/tests/cmph_tests.in b/tests/cmph_tests.in
--- a/tests/cmph_tests.in
+++ b/tests/cmph_tests.in
@@ -9,7 +9,33 @@ test -e _words || head -n "$N"     <"$WORDS" >_words
 test -e _words1000 || head -n 1000 <"$WORDS" >_words1000
 test -e _words100 || head -n 100   <"$WORDS" >_words100
 
-for a in bmz chm brz fch bdz bdz_ph bmz8 chd chd_ph; do
+while getopts "a:f:" opt
+do
+    case "$opt" in
+        a)
+            a="$OPTARG"
+            ;;
+        f)
+            f="$OPTARG"
+            ;;
+        :)
+            echo "Error: Option -$OPTARG requires an argument" >&2
+            exit 1
+            ;;
+    esac
+    shift $((OPTIND-1))
+done
+
+algos="bmz chm brz fch bdz bdz_ph bmz8 chd chd_ph"
+if [ -n "$a" ]; then
+    algos="$a"
+fi
+hashes="jenkins wyhash crc32 fnv djb2 sdbm"
+if [ -n "$f" ]; then
+    hashes="$f"
+fi
+
+for a in $algos; do
     if [ "$a" = "bmz8" ]; then
         rm -f _words100.mph
         words=_words100
@@ -19,7 +45,7 @@ for a in bmz chm brz fch bdz bdz_ph bmz8 chd chd_ph; do
     else
         words=_words
     fi
-    for f in jenkins wyhash crc32 fnv djb2 sdbm; do
+    for f in $hashes; do
         fail=
         echo "** cmph -g -a $a -f $f $words"
         # a retry often helps
